version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      commit-message:
      prefix: "build(#10): update dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      commit-message:
      prefix: "ci(#10): update GitHub Actions"